"""
CMDB数据模型 - 服务器和实例管理
支持175个字段的完整CMDB数据
"""
from sqlalchemy import Column, Integer, String, BigInteger, DateTime, Text, Index, Boolean
from sqlalchemy.sql import func
from app.models.base import Base


class IaasServer(Base):
    """物理服务器表（扩展版 - 支持175个字段）"""
    __tablename__ = "iaas_servers"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    
    # ========== BNS字段（7个）==========
    bns_id = Column(Integer, comment="BNS ID")
    bns_serviceunit = Column(String(255), comment="BNS服务单元")
    bns_hostname = Column(String(255), unique=True, index=True, comment="BNS主机名")
    bns_sn = Column(String(100), comment="BNS序列号")
    bns_ip = Column(String(50), comment="BNS IP地址")
    bns_instancename = Column(String(255), comment="BNS实例名")
    bns_product = Column(String(100), comment="BNS产品")
    
    # ========== RMS字段（37个）- 资源管理系统 ==========
    rms_hostname = Column(String(255), comment="RMS主机名")
    rms_sn = Column(String(100), index=True, comment="RMS序列号")
    rms_cabinetsn = Column(String(100), comment="机柜序列号")
    rms_server_id = Column(String(100), comment="服务器ID")
    rms_suit = Column(String(100), comment="服务器套件")
    rms_type = Column(String(100), comment="服务器类型")
    rms_status = Column(String(50), comment="服务器状态")
    rms_arrive_time = Column(DateTime, comment="到货时间")
    rms_online_time = Column(DateTime, comment="上线时间")
    rms_mod_time = Column(DateTime, comment="修改时间")
    rms_maintenance_time = Column(DateTime, comment="维保时间")
    rms_model = Column(String(100), comment="服务器型号")
    rms_rack_info = Column(String(100), comment="机架位置")
    rms_manufacturer = Column(String(100), comment="制造商")
    rms_idc = Column(String(100), comment="数据中心")
    rms_product = Column(String(100), comment="产品线")
    rms_kernel = Column(String(100), comment="内核版本")
    rms_department = Column(String(100), comment="所属部门")
    rms_ilo_ip = Column(String(100), comment="带外管理IP")
    rms_ilo_mac = Column(String(100), comment="带外管理MAC")
    rms_ip_in1 = Column(String(50), comment="内网IP1")
    rms_ip_in2 = Column(String(50), comment="内网IP2")
    rms_ip_out = Column(String(50), comment="外网IP")
    rms_mac1 = Column(String(50), comment="MAC地址1")
    rms_mac2 = Column(String(50), comment="MAC地址2")
    rms_cpu = Column(Text, comment="CPU配置")
    rms_flash = Column(String(255), comment="Flash存储")
    rms_harddisk = Column(String(255), comment="硬盘配置")
    rms_memory = Column(Text, comment="内存配置")
    rms_networkcard = Column(Text, comment="网卡配置")
    rms_raid = Column(String(255), comment="RAID配置")
    rms_ssd = Column(Text, comment="SSD配置")
    rms_hwfailure_hostname = Column(String(255), comment="硬件故障主机名")
    rms_hwfailure_sn = Column(String(100), comment="硬件故障序列号")
    rms_hwfailure_devices = Column(Text, comment="故障设备")
    rms_hwfailure_details = Column(Text, comment="故障详情")
    rms_hwfailure_op_type = Column(String(50), comment="故障操作类型")
    
    # ========== Nova Host字段（101个）- OpenStack宿主机 ==========
    nova_host_hypervisor_id = Column(String(100), comment="虚拟化ID")
    nova_host_hypervisor_hostname = Column(String(255), comment="虚拟化主机名")
    nova_host_cluster = Column(String(100), comment="集群名称")
    nova_host_node_type = Column(String(50), comment="节点类型")
    nova_host_node_state = Column(String(50), comment="节点状态")
    nova_host_azone = Column(String(100), index=True, comment="可用区")
    nova_host_group_id = Column(String(100), comment="分组ID")
    nova_host_model = Column(String(100), comment="主机型号")
    nova_host_logical_machine_suit = Column(String(100), comment="逻辑机器套件")
    nova_host_machine_suit = Column(String(100), comment="物理机器套件")
    nova_host_hypervisor_type = Column(String(50), comment="虚拟化类型")
    nova_host_physical_memory_mb_total = Column(BigInteger, comment="物理内存总量(MB)")
    nova_host_physical_memory_mb_free = Column(BigInteger, comment="物理内存空闲(MB)")
    nova_host_physical_disk_gb_free = Column(BigInteger, comment="物理磁盘空闲(GB)")
    nova_host_vcpus_total = Column(Integer, comment="虚拟CPU总数")
    nova_host_vcpus_used = Column(Integer, comment="虚拟CPU已用")
    nova_host_vcpus_free = Column(Integer, comment="虚拟CPU空闲")
    nova_host_running_vms = Column(Integer, comment="运行中虚拟机数")
    nova_host_physical_cpus = Column(Integer, comment="物理CPU数")
    nova_host_host_ip = Column(String(50), comment="主机IP")
    nova_host_hypervisor_version = Column(String(50), comment="虚拟化版本")
    nova_host_net_bandwidth_kbps = Column(BigInteger, comment="网络带宽(Kbps)")
    nova_host_blacklisted_expired_at = Column(DateTime, comment="黑名单过期时间")
    nova_host_arrive_time = Column(DateTime, comment="到货时间")
    nova_host_service_id = Column(String(100), comment="服务ID")
    nova_host_uuid = Column(String(100), comment="主机UUID")
    nova_host_user_id = Column(String(100), comment="用户ID")
    nova_host_cpu_allocation_ratio = Column(String(50), comment="CPU分配比例")
    nova_host_netbandwidth_allocation_ratio = Column(String(50), comment="网络带宽分配比例")
    nova_host_enable_dpdk = Column(Boolean, comment="启用DPDK")
    nova_host_enable_numa = Column(Boolean, comment="启用NUMA")
    nova_host_enable_turbo = Column(Boolean, comment="启用Turbo")
    nova_host_enable_bind_core = Column(Boolean, comment="启用核心绑定")
    nova_host_tor_ips = Column(Text, comment="TOR交换机IP(JSON)")
    nova_host_has_pci = Column(Boolean, comment="是否有PCI设备")
    nova_host_cds_version = Column(String(50), comment="CDS版本")
    nova_host_cpuid_md5 = Column(String(100), comment="CPU ID MD5")
    nova_host_qemu_version = Column(String(50), comment="QEMU版本")
    nova_host_libvirt_version = Column(String(50), comment="Libvirt版本")
    nova_host_kernel_version = Column(String(100), comment="内核版本")
    nova_host_net_bandwidth = Column(String(50), comment="网络带宽")
    nova_host_disk_bandwidth = Column(String(50), comment="磁盘带宽")
    nova_host_cpu_set = Column(Text, comment="CPU集合")
    nova_host_vcpus_dedicated = Column(Integer, comment="专用虚拟CPU")
    nova_host_memory_mb_dedicated = Column(BigInteger, comment="专用内存(MB)")
    nova_host_local_gb_dedicated = Column(BigInteger, comment="专用本地存储(GB)")
    nova_host_project_id = Column(String(100), comment="项目ID")
    nova_host_name = Column(String(255), comment="主机名称")
    nova_host_blacklisted_description = Column(Text, comment="黑名单描述")
    nova_host_blacklisted_reason = Column(String(255), comment="黑名单原因")
    nova_host_cpu_info = Column(Text, comment="CPU详细信息(JSON)")
    nova_host_scheduler_label = Column(Text, comment="调度标签(JSON)")
    nova_host_disks = Column(Text, comment="磁盘信息(JSON)")
    nova_host_pci_devices = Column(Text, comment="PCI设备(JSON)")
    nova_host_sn = Column(String(100), comment="序列号")
    nova_host_memory_mb = Column(BigInteger, comment="内存(MB)")
    nova_host_local_gb = Column(BigInteger, comment="本地存储(GB)")
    nova_host_ilo_ip = Column(String(100), comment="带外管理IP")
    nova_host_bond_mac = Column(String(100), comment="Bond MAC地址")
    nova_host_interfaces = Column(Text, comment="网络接口(JSON)")
    nova_host_tor_if = Column(String(100), comment="TOR接口")
    nova_host_tor_name = Column(String(100), comment="TOR名称")
    nova_host_created_at = Column(DateTime, comment="创建时间")
    nova_host_updated_at = Column(DateTime, comment="更新时间")
    nova_host_assigned_at = Column(DateTime, comment="分配时间")
    
    # ========== 系统字段 ==========
    created_at = Column(DateTime, server_default=func.now(), comment="记录创建时间")
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now(), comment="记录更新时间")
    synced_at = Column(DateTime, comment="最后同步时间")


class IaasInstance(Base):
    """虚拟实例表（扩展版 - 支持175个字段）"""
    __tablename__ = "iaas_instances"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    
    # ========== 关联字段 ==========
    bns_hostname = Column(String(255), index=True, comment="所属主机名")
    
    # ========== Nova VM字段（30+个）- 虚拟机实例 ==========
    nova_vm_instance_uuid = Column(String(100), unique=True, index=True, comment="实例UUID")
    nova_vm_display_name = Column(String(255), comment="显示名称")
    nova_vm_hypervisor_hostname = Column(String(255), comment="宿主机名")
    nova_vm_cluster = Column(String(100), comment="集群")
    nova_vm_azone = Column(String(100), comment="可用区")
    nova_vm_user_id = Column(String(100), index=True, comment="用户ID")
    nova_vm_tenant_id = Column(String(255), comment="租户ID")  # 扩展到255以支持多租户ID
    nova_vm_metadata_source = Column(String(100), comment="元数据来源")
    nova_vm_os_type = Column(String(50), comment="操作系统类型")
    nova_vm_flavor_id = Column(String(100), comment="规格ID")
    nova_vm_vcpus = Column(Integer, comment="虚拟CPU数")
    nova_vm_memory_mb = Column(Integer, comment="内存(MB)")
    nova_vm_root_gb = Column(Integer, comment="根磁盘(GB)")
    nova_vm_ephemeral_gb = Column(Integer, comment="临时磁盘(GB)")
    nova_vm_hypervisor_dedicated = Column(Boolean, comment="专用虚拟化")
    nova_vm_project_id = Column(String(100), comment="项目ID")
    nova_vm_instance_name = Column(String(255), comment="实例名称")
    nova_vm_image_uuid = Column(String(100), comment="镜像UUID")
    nova_vm_max_net_bandwidth_kbps = Column(BigInteger, comment="最大网络带宽(Kbps)")
    nova_vm_metadata_ephemeral_raw = Column(String(50), comment="临时存储元数据")
    nova_vm_metadata_root_on_cds_v2 = Column(String(50), comment="根磁盘在CDS V2")
    nova_vm_metadata_root_on_cds = Column(String(50), comment="根磁盘在CDS")
    nova_vm_metadata_roc_status = Column(String(50), comment="ROC状态")
    nova_vm_power_state = Column(Integer, comment="电源状态")
    nova_vm_root_device_name = Column(String(100), comment="根设备名")
    nova_vm_root_volume_id = Column(String(100), comment="根卷ID")
    nova_vm_task_state = Column(String(50), comment="任务状态")
    nova_vm_vm_state = Column(String(50), index=True, comment="虚拟机状态")
    nova_vm_subnets = Column(Text, comment="子网(JSON)")
    nova_vm_floating_ips = Column(Text, comment="浮动IP(JSON)")
    nova_vm_fixed_ips = Column(Text, comment="固定IP(JSON)")
    nova_vm_virtual_disks = Column(Text, comment="虚拟磁盘(JSON)")
    nova_vm_volumes_attached = Column(Text, comment="挂载卷(JSON)")
    nova_vm_created_at = Column(DateTime, comment="虚拟机创建时间")
    nova_vm_updated_at = Column(DateTime, comment="虚拟机更新时间")
    nova_vm_launched_at = Column(DateTime, comment="虚拟机启动时间")
    
    # ========== Logical字段（15个）- 逻辑实例 ==========
    logical_instance_id = Column(String(100), comment="逻辑实例ID")
    logical_instance_uuid = Column(String(100), comment="逻辑实例UUID")
    logical_region = Column(String(100), comment="逻辑区域")
    logical_deleted = Column(Boolean, comment="是否删除")
    logical_roc_v2 = Column(String(50), comment="ROC V2")
    logical_user_id = Column(String(100), comment="逻辑用户ID")
    logical_tenant_id = Column(String(100), comment="逻辑租户ID")
    logical_name = Column(String(255), comment="逻辑名称")
    logical_internal_ip = Column(String(50), comment="内部IP")
    logical_floating_ip = Column(String(50), comment="浮动IP")
    logical_status = Column(String(50), comment="逻辑状态")
    logical_order_uuid = Column(String(100), comment="订单UUID")
    logical_dcc_uuid = Column(String(100), comment="DCC UUID")
    logical_source = Column(String(100), comment="来源")
    logical_application = Column(String(100), comment="应用")
    
    # ========== CRM字段（15个）- 客户关系管理 ==========
    crm_accountId = Column(String(100), comment="账户ID")
    crm_loginName = Column(String(255), index=True, comment="登录名")
    crm_registerTime = Column(DateTime, comment="注册时间")
    crm_name = Column(String(255), comment="账户名称")
    crm_cname = Column(String(255), comment="中文名称")
    crm_serviceAccount = Column(String(100), comment="服务账户")
    crm_province = Column(String(100), comment="省份")
    crm_city = Column(String(100), comment="城市")
    crm_company = Column(String(500), comment="公司名称")
    crm_vip_type = Column(String(50), comment="VIP类型")
    crm_industry = Column(String(100), comment="行业")
    crm_industryDetail = Column(String(255), comment="行业详情")
    crm_accountManagers = Column(Text, comment="客户经理(JSON)")
    crm_techniqueAccountManagers = Column(Text, comment="技术客户经理(JSON)")
    crm_tags = Column(Text, comment="标签(JSON)")
    
    # ========== 系统字段 ==========
    created_at = Column(DateTime, server_default=func.now(), comment="记录创建时间")
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now(), comment="记录更新时间")
    synced_at = Column(DateTime, comment="最后同步时间")
    
    __table_args__ = (
        Index('idx_hostname_state', 'bns_hostname', 'nova_vm_vm_state'),
        Index('idx_user_id', 'nova_vm_user_id'),
        Index('idx_crm_login', 'crm_loginName'),
    )
